DMDirc/dmdirc3

src/main/kotlin/Connection.kt
- Use non-deprecated way to get times from KtIrc events
- Show actions
- Show quits more sensibly, and per-channel
- Add some utility methods to reduce boilerplate
=> Improve text handling a little

build.gradle.kts, src/main/kotlin/Config.kt, src/main/kotlin/ConnectDialog.kt, src/test/kotlin/ConfigTest.kt
=> Use Konf for reading/writing our config.

.gitignore, src/main/kotlin/Config.kt, src/main/kotlin/ConnectDialog.kt, src/main/kotlin/MainView.kt
Auto connect isn't functional.
=> Add basic serverlist

src/main/kotlin/Config.kt, src/main/kotlin/Connection.kt, src/main/kotlin/MainController.kt, src/main/kotlin/SettingsDialog.kt, src/test/kotlin/SettingsDialogTest.kt, src/test/resources/io/mockk/settings.properties
=> Use new config system for profiles

src/main/kotlin/Config.kt, src/main/kotlin/ConnectDialog.kt, src/main/kotlin/MainController.kt, src/main/kotlin/MainView.kt, src/main/kotlin/WindowUI.kt
=> Autoconnect to servers

src/main/kotlin/Connection.kt, src/main/kotlin/MainController.kt, src/main/kotlin/MainView.kt, src/main/kotlin/WindowUI.kt
=> Sort Windows.

src/main/kotlin/Connection.kt, src/main/kotlin/ControlCodes.kt, src/test/kotlin/ControlCodesTest.kt
This does everything except the colour-related ones
(colour, hex colour, reverse) for now.
Classes are applied to the text but we don't yet have
styles for them.
Issue #8
=> Add initial control code handling

src/main/kotlin/ControlCodes.kt, src/test/kotlin/ControlCodesTest.kt
=> Add handling of colour codes

.gitignore, src/main/kotlin/Connection.kt, src/main/kotlin/MainController.kt, src/main/kotlin/MainView.kt, src/main/kotlin/WindowUI.kt
=> Add connection ID for connections, use it for sorting

src/main/kotlin/Connection.kt, src/main/kotlin/MainController.kt, src/main/kotlin/MainView.kt
=> Context menu for closing windows.

src/main/kotlin/MainView.kt, src/main/kotlin/Stylesheets.kt, src/main/kotlin/WindowUI.kt, src/main/resources/stylesheet.css
Tidy up some of the layouts, maybe fix error when reloading
stylesheets.
=> Flesh out a default stylesheet a bit more

src/main/kotlin/App.kt, src/main/resources/logs.properties
Enables FINE logging for com.dmdirc.* (including KtIrc), everything
else is WARNING.
=> Add a logging properties file

src/main/kotlin/Config.kt, src/main/kotlin/Connection.kt, src/main/kotlin/ControlCodes.kt, src/main/resources/stylesheet.css
Read the timestamp format from the config
Apply a 'timestamp' class to the timestamp so it can be styled
Also add !important to font properties so they're not overwritten by custom font families
Closes #44
=> Custom timestamp formatting

README.md, build.gradle.kts, src/main/kotlin/App.kt, src/main/kotlin/Config.kt, src/main/kotlin/ConnectDialog.kt, src/main/kotlin/Connection.kt, src/main/kotlin/JoinDialog.kt, src/main/kotlin/MainView.kt, src/main/kotlin/SettingsDialog.kt, translations/en_BW/messages.po, translations/en_GB/messages.po, translations/en_US/messages.po, translations/messages.pot
Using gettext to find all the strings and dump them to a file,
then crowdin can take the file offer it to translators and
export the result. We should be able to automate the whole
process fairly easily.
=> First pass at i18n

src/main/kotlin/Connection.kt, src/main/kotlin/ControlCodes.kt, src/main/kotlin/IrcTextArea.kt, src/main/kotlin/WindowUI.kt, src/main/resources/stylesheet.css
Also switch to a GenericStyledArea so we can do images in the future.
Closes #9
=> Super basic link handling

src/main/kotlin/ControlCodes.kt, src/main/kotlin/IrcTextArea.kt, src/main/resources/stylesheet.css, src/test/kotlin/ControlCodesTest.kt
Mark all colours in the default stylesheet as !important so
they don't get boshed by a user changing the default text
colour :/
=> Support hex colours

build.gradle.kts, src/main/kotlin/App.kt, src/main/kotlin/JoinDialog.kt, src/main/kotlin/Validating.kt, src/test/kotlin/SettingsDialogTest.kt
Almost everything still uses it, but the JoinDialog does not.  Definitely needs some layout tweaks done but functionally working.
=> Start removing tornadofx

.drone.yml, README.md, build.gradle.kts, src/main/kotlin/App.kt, translations/messages.pot
- Add code coverage and upload to codecov
- Add build & coverage badges to README
- Update command for translations to make the diff a bit nicer
- Update translations
- Minor tidying
=> Tidying, coverage, translations

src/main/kotlin/com/dmdirc/ControlCodes.kt, src/test/kotlin/com/dmdirc/ControlCodesTest.kt
Simplify some logic that was always true.
=> Add some extra control code tests

src/main/kotlin/com/dmdirc/Connection.kt, src/main/kotlin/com/dmdirc/MainController.kt, src/main/kotlin/com/dmdirc/MainView.kt, src/main/kotlin/com/dmdirc/WindowUI.kt
Connection now tracks its children instead of lobbing them at
the MainController.
=> Refactor connection and window management a bit

src/main/kotlin/com/dmdirc/App.kt, src/main/kotlin/com/dmdirc/Connection.kt, src/main/kotlin/com/dmdirc/MainController.kt, src/main/kotlin/com/dmdirc/MainView.kt
- Connection now exposes an observable of its children, instead
of calling out to the main controller every time
- Connection's own model/ui is now put in children as well
- Inject a factory for connections into MainController instead
of creating them directly
=> Tidy how connections work

src/main/kotlin/com/dmdirc/ControlCodes.kt, src/main/kotlin/com/dmdirc/IrcTextArea.kt, src/test/kotlin/com/dmdirc/ControlCodesTest.kt, src/test/kotlin/com/dmdirc/IrcTextAreaTest.kt, src/test/kotlin/com/dmdirc/WindowModelTest.kt
This allows pseudo-random nick colouring like in other clients.
Closes #102
=> Add a "colour hash" style to nicknames

src/main/kotlin/com/dmdirc/Connection.kt, src/main/kotlin/com/dmdirc/WindowUI.kt, src/test/kotlin/com/dmdirc/WindowModelTest.kt
=> Super primitive action sending

src/main/kotlin/com/dmdirc/App.kt, src/main/kotlin/com/dmdirc/Config.kt, src/test/kotlin/com/dmdirc/ConfigTest.kt
=> Use a proper config directory

src/main/kotlin/com/dmdirc/Config.kt, src/main/kotlin/com/dmdirc/Connection.kt, src/main/kotlin/com/dmdirc/WindowUI.kt, src/test/kotlin/com/dmdirc/WindowModelTest.kt
=> Show notices

dmdirc.install4j
Launchers already support auto updating.  Need to add some support in the client for scheduling auto update checks and/or manually checking.
=> Add an automatic background updater.

src/main/kotlin/com/dmdirc/MainView.kt, src/main/kotlin/com/dmdirc/WindowUI.kt, src/main/resources/stylesheet.css
=> Track and show unread messages

src/main/kotlin/com/dmdirc/Connection.kt
=> Auto change nick if it's in use when connecting

src/main/kotlin/com/dmdirc/MainView.kt, src/main/kotlin/com/dmdirc/WindowUI.kt, src/main/resources/stylesheet.css
=> Show disconnected windows with a strikethrough

src/main/kotlin/com/dmdirc/Connection.kt, src/main/kotlin/com/dmdirc/MainView.kt
Separate close from disconnect.
Closes #169
=> Add ability to disconnect/reconnect to servers.

src/main/kotlin/com/dmdirc/Connection.kt, src/main/kotlin/com/dmdirc/MainController.kt, src/main/kotlin/com/dmdirc/MainView.kt, src/test/kotlin/com/dmdirc/MainControllerTest.kt
=> Auto select servers when adding.

src/main/kotlin/com/dmdirc/WindowUI.kt
Closes #43
Getting the scrollbar is a little nasty and does make some assumptions, but I think will gracefully fail if they make changes.
=> Add autoscroll.

build.gradle.kts
=> Exclude a couple of dependencies

src/main/kotlin/com/dmdirc/Connection.kt
=> Re-use channel windows if they exist.

src/main/kotlin/com/dmdirc/ServerlistDialog.kt
Connect and Delete are now next to the add button.
=> Move buttons in the serverlist dialog

src/main/kotlin/com/dmdirc/WindowUI.kt, src/test/kotlin/com/dmdirc/WindowModelTest.kt
=> Update the input field on the right thread

src/main/kotlin/com/dmdirc/IrcTextArea.kt
=> Fix images having inconsistent text representation

src/main/kotlin/com/dmdirc/App.kt, src/main/kotlin/com/dmdirc/Config.kt, src/main/kotlin/com/dmdirc/FxUtils.kt, src/test/kotlin/com/dmdirc/FxUtilsTest.kt
=> Add config setting for turning off error reporting

src/main/kotlin/com/dmdirc/App.kt, src/main/kotlin/com/dmdirc/Connection.kt, src/main/kotlin/com/dmdirc/FocusManager.kt, src/main/kotlin/com/dmdirc/MainView.kt, src/main/kotlin/com/dmdirc/WindowUI.kt
=> Always focus the input field.  I think.

src/main/kotlin/com/dmdirc/FocusManager.kt
=> Check if listener is null before removing.

src/main/kotlin/com/dmdirc/WindowUI.kt
=> Rework autoscroll.

src/main/kotlin/com/dmdirc/WindowUI.kt, src/main/resources/stylesheet.css, src/test/kotlin/com/dmdirc/WindowModelTest.kt
Add default colours for messages/actions/notices and generic channel and
server events.
Closes #31
Closes #101
=> Add styles for MessageFlags

src/main/kotlin/com/dmdirc/MainView.kt
=> Fix odd binding logic in treeview context menu.

src/main/kotlin/com/dmdirc/IrcEventMapper.kt, src/main/kotlin/com/dmdirc/MainView.kt, src/main/kotlin/com/dmdirc/WindowUI.kt, src/main/resources/stylesheet.css, src/test/kotlin/com/dmdirc/WindowModelTest.kt
General events are now grey
Messages blue
Highlights (when they're implemented) red
Also fix the text colour of selected treeview nodes
Closes #192
=> Show different notification colours per event

CHANGELOG.adoc, LICENSE.adoc, build.gradle.kts
=> Update KtIrc, add changelog

CHANGELOG.adoc, src/main/kotlin/com/dmdirc/App.kt, src/main/kotlin/com/dmdirc/Connection.kt, src/main/kotlin/com/dmdirc/IrcEventMapper.kt, src/main/kotlin/com/dmdirc/MainController.kt, src/main/kotlin/com/dmdirc/NotificationManager.kt, src/main/kotlin/com/dmdirc/WindowUI.kt, src/main/resources/stylesheet.css, src/test/kotlin/com/dmdirc/MainControllerTest.kt, src/test/kotlin/com/dmdirc/WindowModelTest.kt
Any action/notice/message containing the current nick gets styled as a
highlight. Highlights trigger a notification. Notifications get
reported to stdout for now.
Issue #103
=> Basic highlighting

src/main/kotlin/com/dmdirc/MainView.kt
=> Select the initially selected window.

CHANGELOG.adoc, build.gradle.kts, src/main/kotlin/com/dmdirc/App.kt, src/main/kotlin/com/dmdirc/Connection.kt, src/main/kotlin/com/dmdirc/ImageLoader.kt, src/main/kotlin/com/dmdirc/IrcTextArea.kt, src/main/kotlin/com/dmdirc/WindowUI.kt
This uses okhttp.
This no longer has a progress bar.
=> Load images following redirects.

src/main/kotlin/com/dmdirc/MainView.kt, src/main/resources/stylesheet.css
=> Swap borderpane for stackpane in treeview.  Cog always on right.

src/main/kotlin/com/dmdirc/MainView.kt, src/main/kotlin/com/dmdirc/WindowUI.kt
Create a getTitle function in WindowModel.
Probably should be made a property so it can be observed.
Closes #257
=> Set the title on the initial auto connect.

CHANGELOG.adoc, src/main/kotlin/com/dmdirc/WindowUI.kt, src/main/resources/stylesheet.css
Fix the random blank line at the bottom of the textpane
=> Make text in the textpane start at the bottom

CHANGELOG.adoc, src/main/kotlin/com/dmdirc/App.kt
=> Fix errors not being reported during startup

src/main/kotlin/com/dmdirc/App.kt, src/main/kotlin/com/dmdirc/JoinDialog.kt, src/main/kotlin/com/dmdirc/MainView.kt, src/main/kotlin/com/dmdirc/ServerlistDialog.kt, src/main/kotlin/com/dmdirc/SettingsDialog.kt
Remove the amazing recursive horrible.
Closes #270
=> Rework dialog transitions.

dmdirc.install4j
=> Changes to installer
